server:
 port: 18081
spring:
 application:
  name: tsf-provider

provider:
 config:
  name: test11111

tsf:
  swagger:
    enabled: true

#  关闭hystrix
feign:
 hystrix:
  enabled: false

#公共自定义配置
global:
 config:
  name: 1234567
