server:
 port: 18081
spring:
 application:
  name: tsf-provider

provider:
 config:
  name: Provider-Config-12345678

tsf:
  swagger:
    enabled: true

# 关闭hystrix
feign:
 hystrix:
  enabled: false

#公共自定义配置
global:
 config:
  name: Global-Config-12345678

##springboot日志
#logging:
# file: /var/root.log

#日志path
logging:
  path: /data/tsf_logs
